# Generated by Django 5.1 on 2024-10-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='question_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
