# Generated by Django 5.1 on 2026-01-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='supabase_id',
            field=models.CharField(blank=True, help_text='Supabase認証を使用する場合のユーザーID', max_length=255, null=True, unique=True, verbose_name='Supabase ユーザーID'),
        ),
    ]
