"""
Django settings for wordbook project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import django_heroku
import dj_database_url
import os
from pathlib import Path
from decouple import config
from django.contrib.messages import constants as messages
from logging.handlers import RotatingFileHandler


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# ===== 🆕 Supabase設定 =====
SUPABASE_URL = config('SUPABASE_URL')
SUPABASE_JWT_SECRET = config('SUPABASE_JWT_SECRET')

if not SUPABASE_JWT_SECRET:
    raise ValueError('SUPABASE_JWT_SECRET must be set in .env file')
# ============================

# デバッグ設定の読み込み（存在しない場合はデフォルトでFalse）
DEBUG = config("DEBUG", default=False, cast=bool)

# 接続を許可するホストをローカルとherokuのアドレスに固定
ALLOWED_HOSTS = [
    config("ALLOWED_HOSTS", default="").split(",")
    # "flashcard-tamk-ed931c69d79f.herokuapp.com",
    # "flashcard.toamoku.net",
    # "localhost",
    # "127.0.0.1",
]

CORS_ALLOWED_ORIGINS = [
    config("CORS_ALLOWED_ORIGINS", default="").split(",")
    # "http://localhost:3000",
    # "https://https://wordbook-frontend-five.vercel.app/",
]
CORS_ALLOW_CREDENTIALS = True

# Application definition

# ===== 🆕 REST Framework設定 =====
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'config.authentication.SupabaseAuthentication',  # 🆕 Supabase JWT認証
        'rest_framework.authentication.SessionAuthentication',  # 既存のセッション認証
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}
# ============================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "contact",
    "dictionary",
    "flashcard",
    "error",
    "csp",
    "rest_framework",
    "corsheaders",
]

AUTH_USER_MODEL = "accounts.CustomUser"

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"


ROOT_URLCONF = "wordbook.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR, "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wordbook.wsgi.application"

# Herokuのデプロイ環境で設定を自動調整
django_heroku.settings(locals())

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# ローカル開発用のデータベース設定（SQLiteなど）

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# 本番環境用のデータベース設定
DATABASE_URL = config("DATABASE_URL")
if DATABASE_URL:
    DATABASES["default"] = dj_database_url.config(
        default=DATABASE_URL, conn_max_age=600, ssl_require=True
    )


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators


# ターミナルで仮想環境を有効化してからpip install argon2-cffiを実行し、argon2を有効化する
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.BCryptPasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
]

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "ja"

TIME_ZONE = "Asia/Tokyo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# 本番環境で静的ファイルを提供するディレクトリ
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

LOGIN_URL = "/login/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


MESSAGE_TAGS = {
    messages.DEBUG: "alert-secondary",
    messages.INFO: "alert-info",
    messages.SUCCESS: "alert-success",
    messages.WARNING: "alert-warning",
    messages.ERROR: "alert-danger",
}


# EMIL設定
# 開発環境用のメール設定
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# 実運用時には以下のようにSMTPメールサーバーを設定します
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")

# セキュリティ設定

# HTTPSリダイレクトを強制する。（開発中はFalseで設定）
SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=True, cast=bool)

# HSTSヘッダーを設定する
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# X-Frame-Optionsヘッダーを設定する
X_FRAME_OPTIONS = "DENY"

# X-Content-Type-Optionsヘッダーを設定する
SECURE_CONTENT_TYPE_NOSNIFF = True

# X-XSS-Protectionヘッダーを設定する
SECURE_BROWSER_XSS_FILTER = True

# プロキシサーバーからのSSLヘッダーを設定する
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# セッションとCSRF保護の設定
# セッションとCSRFクッキーをHTTPS経由でのみ送信する
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# ブラウザが不正なファイルの種類での解釈を防ぐ
SECURE_CONTENT_TYPE_NOSNIFF = True


# Content Security Policyの設定

CSP_DEFAULT_SRC = ("'self'",)  # 自分のドメインのみ許可
CSP_SCRIPT_SRC = (
    "'self'",
    "https://cdn.jsdelivr.net",  # Bootstrap JavaScript
)
CSP_STYLE_SRC = (
    "'self'",
    "https://cdn.jsdelivr.net",  # Bootstrap CSS
    "https://fonts.googleapis.com",  # Google Fonts CSS
)
CSP_FONT_SRC = (
    "'self'",
    "https://fonts.gstatic.com",  # Google Fontsのフォント用
)


# ロギングの設定

# プロジェクトルートを基準にしたログディレクトリ
LOG_DIR = os.path.join(BASE_DIR, "logs")
# ログディレクトリが存在しない場合は作成
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "rotating_file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "django.log"),
            "formatter": "verbose",
            "maxBytes": 1024 * 1024 * 5,  # 5MB
            "backupCount": 5,  # バックアップとして保存するファイル数
        },
        "error_file": {  # エラーログ専用
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": os.path.join(LOG_DIR, "error.log"),
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {  # 全般ログ
            "handlers": ["rotating_file"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {  # エラーログ専用
            "handlers": ["error_file"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}
