# Generated by Django 5.1 on 2024-10-21 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_level_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='english',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='英語'),
        ),
        migrations.AlterField(
            model_name='word',
            name='japanese',
            field=models.CharField(db_index=True, max_length=255, verbose_name='日本語'),
        ),
        migrations.AlterField(
            model_name='word',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='dictionary.level', verbose_name='難易度'),
        ),
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_of_speech', to='dictionary.partofspeech', verbose_name='品詞'),
        ),
    ]
